// <auto-generated />
namespace UniversityManagementSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_savestudentresult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_savestudentresult));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131712491_Create_savestudentresult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
